version: "3"
services:
  nodejs:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    container_name: node_api_part_of_speech
    volumes:
      - ./backend:/usr/src/POS/backend
      - /usr/src/POS/backend/node_modules/

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: react_part_of_speech
    volumes:
      - ./frontend:/usr/src/POS/frontend
      - /usr/src/POS/frontend/node_modules/
